### ISSUE TITLE
Cannot import on 2020.3

### ISSUE THREAD

**Issue by Morgan-6Freedom** [javierfoe/Multiplayer-Bluetooth-Unity#1]
Hello.
This is what I did :

1. Start a new Unity 2020.3 project
2. Download your repo as a zip
3. Copy the /AndroidBluetoothMultiplayer/ Folder in my /Assets/ folder
4. Download mirror with the link in your readme
5. Import the package
5. Download Ignorance with the link in your readme
6. Import the package

This is what I got :
![image](https://user-images.githubusercontent.com/49686866/128505871-43b89156-69e7-4b72-8cfe-55c85db24255.png)

**Comment by javierfoe** [comment]
Hello Morgan-6Freedom,

It's been tested on 2019.3.11f1, if it doesn't work there I can check it. I have plans in the future to keep this updated to the latest versions of Mirror, Ignorance and Unity. Thank you for your message.

Best Regards,

javierfoe.

**Comment by javierfoe** [comment]
I tested it on the Unity 2019 LTS and it should work.

**Comment by javierfoe** [comment]
I updated the repository. Now it definitely works on 2020 LTS. Give it a try and let me know if you have any issues.
