### ISSUE TITLE
help with unity integration

### ISSUE THREAD

**Issue by monky822** [javierfoe/Multiplayer-Bluetooth-Unity#2]
Hi Javier,

I followed your instructions and I'm getting quite a few errors including:

namespace name 'BluetoothDevice' could not be found
javierfoe.Blueberry.Internal; does not exist
What to replace NetworkView with?

Do you have a guide on this?

**Comment by javierfoe** [comment]
I tried it on a fresh Unity 2021.3.2f1 installation, downloaded the code, unzipped it, downloaded the Mirror version that is on the readme and unpacked it directly in Unity, and the same with the Ignorance version and I have no errors.

**Comment by javierfoe** [comment]
The steps would be:

- Download blueberry, the latest commit, not the release, unzip it.
- Open the unzipped folder on Unity 2021.3.2f1
- Download the mirror version from the readme, unpack it directly in the Project tab inside Unity.
- The same with Ignorance.

**Comment by monky822** [comment]
I will try again with the latest version of Unity 2021

After the Ignorance import do I need to also: 

1)  "Android Bluetooth Multiplayer (Basic)" asset

2) Replace all instances of "UnityEngine.Networking" with "Mirror"

**Comment by javierfoe** [comment]
You don't have to deal with any UnityEngine.Networking imports nor the original asset.

**Comment by monky822** [comment]
Awesome. That was the problem. I purchased the old bluetooth multiplayer asset and I was trying to replace old code.

Thank you!

**Comment by javierfoe** [comment]
My pleasure. I close the issue :P
