### ISSUE TITLE
Bluetooth Manager HUD Does Not Get Initialized

### ISSUE THREAD

**Issue by monky822** [javierfoe/Multiplayer-Bluetooth-Unity#3]
I tested all your sample scenes. None of them have the BluetoothManagerHUD showing up.

void OnGUI()
        {
            if (!manager.IsInitialized) return;

The error occurs at the manager is not being initialized (the line seen above). 

I tested in Unity 2020 and 2021. 

I'm also testing in the editor.

I will test on an actual Android device and report back...

EDIT: I tested on android and it works.

Is it possible to make it work my PC bluetooth and an Android device?

**Comment by JFriasOrtiz** [comment]
This asset only works between Android bluetooth devices, that's a feature I'm also seeking, but unfortunately it is not the case here.
